// Get all actors
GET http://localhost:5000/actors

###

// Get actor by id
GET http://localhost:5000/actors/3

###

// Create actor
POST http://localhost:5000/actors HTTP/1.1
content-type: application/json

{ 
    "id": 5,
    "full_name": "New actor",
    "nationality": "United States of America",
    "photo": "",
    "biography": "Info about the actor",
    "birth_date": "1970-01-01",
    "death_date": ""
}

###

// Update actor
PUT http://localhost:5000/actors/1 HTTP/1.1
content-type: application/json

{
    "id": 1,
    "full_name": "Updated actor",
    "nationality": "United States of America",
    "photo": "",
    "biography": "Updated info about the actor",
    "birth_date": "1970-01-01",
    "death_date": "2024-01-01"
}

###

// Delete actor
DELETE  http://localhost:5000/actors/2 HTTP/1.1
