// Get all actors
GET http://localhost:5000/actors

###

// Get actor by id
GET http://localhost:5000/actors/3

###

// Create actor
POST http://localhost:5000/actors HTTP/1.1
content-type: application/json

{
  "full_name": "Test actor",
  "birth_year": "2000-01-01",
  "nationality": "USA"
}

###

// Update actor
PUT http://localhost:5000/actors HTTP/1.1
content-type: application/json

{
  "full_name": "Updated actor",
  "birth_year": "2000-01-01",
  "nationality": "FR",
  "actor_id": 1
}

###

// Delete actor
DELETE  http://localhost:5000/actors/101 HTTP/1.1
