// Get all directors
GET http://localhost:5000/api/directors

###

// Get director by id
GET http://localhost:5000/api/directors/3

###

// Create director
POST http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "full_name": "Test director",
  "birth_year": "2000-01-01",
  "nationality": "USA"
}

###

// Update director
PUT http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "full_name": "Updated director",
  "birth_year": "2000-01-01",
  "nationality": "UA",
  "director_id": 1
}

###

// Delete director
DELETE  http://localhost:5000/api/directors/12 HTTP/1.1
