// Get all movies
GET http://localhost:5000/api/movies

###

// Get movie by id
GET http://localhost:5000/api/movies/3

###

// Create movie (Success)
POST http://localhost:5000/api/movies HTTP/1.1
content-type: application/json

{ 
    "title": "New movie",
    "release_year": "2023-01-01",
    "poster": null,
    "genre": "Fantazy",
    "studio": "Universal Studio"
}

###

// Create movie (With error)
POST http://localhost:5000/api/movies HTTP/1.1
content-type: application/json

{ 
    "title": "N",
    "release_year": "2025-01-01",
    "poster": null,
    "genre": "Fantazy",
    "studio": "Universal Studio"
}

###

// Update movie
PUT http://localhost:5000/api/movies HTTP/1.1
content-type: application/json

{
    "movie_id": 20,
    "title": "Updated movie",
    "release_year": "2010-01-01",
    "poster": null,
    "genre": "Action",
    "studio": "Universal Studio"
}

###

// Delete movie
DELETE  http://localhost:5000/api/movies/20 HTTP/1.1
