### Get all countries
GET http://localhost:5000/api/countries

### Get country by id
GET http://localhost:5000/api/countries/3

### Create country
POST http://localhost:5000/api/countries HTTP/1.1
content-type: application/json

{
  "title": "New country"
}

### Update country
PUT http://localhost:5000/api/countries HTTP/1.1
content-type: application/json

{
  "id": 40,
  "title": "Updated country"
}

### Delete country
DELETE  http://localhost:5000/api/countries/40 HTTP/1.1
