// Get all directors
GET http://localhost:5000/api/directors

###

// Get director by id
GET http://localhost:5000/api/directors/3

###

// Create director (Success)
POST http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "full_name": "Test director",
  "birth_year": "2000-01-01",
  "nationality": "USA"
}

###

// Create director (With errors)
POST http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "full_name": "T",
  "birth_year": "1850-01-01",
  "death_year": "null",
  "nationality": "GB"
}

###

// Update director
PUT http://localhost:5000/api/directors HTTP/1.1
content-type: application/json

{
  "full_name": "Updated director",
  "birth_year": "2000-01-01",
  "nationality": "UA",
  "director_id": 1
}

###

// Delete director
DELETE  http://localhost:5000/api/directors/12 HTTP/1.1
