### Get all locations (default pagination)
GET http://localhost:5000/api/locations

### Get all locations (custom pagination)
GET http://localhost:5000/api/locations?_page=1&_limit=5

### Get location by id
GET http://localhost:5000/api/locations/3

### Create location
POST http://localhost:5000/api/locations HTTP/1.1
content-type: application/json

{
  "title": "New location",
  "country": "United States of America",
  "coat_of_arms": ""
}

### Update location
PUT http://localhost:5000/api/locations HTTP/1.1
content-type: application/json

{
  "id": 11,
  "title": "Updated location",
  "country": "France",
  "coat_of_arms": null
}

### Patch location
PATCH http://localhost:5000/api/locations/11 HTTP/1.1
content-type: application/json

{
  "title": "Patched location",
  "country": "Ukraine",
  "coat_of_arms": null
}

### Delete location
DELETE  http://localhost:5000/api/locations/11 HTTP/1.1
