### Get all movies (default pagination)
GET http://localhost:5000/api/movies

### Get all movies (custom pagination)
GET http://localhost:5000/api/movies?_page=1&_limit=10

### Get movie by id
GET http://localhost:5000/api/movies/3

### Create movie
POST http://localhost:5000/api/movies HTTP/1.1
content-type: application/json

{
  "title": "New movie",
  "genre": "Action",
  "release_year": 2024,
  "poster": null,
  "trailer": null,
  "storyline": null,
  "actors": ["Harrison Ford", "Johnny Depp", "Sigourney Weaver"], 
  "directors": ["Steven Spielberg"],  
  "studios": ["Lucasfilm Ltd."]     
}

### Update movie
PUT http://localhost:5000/api/movies HTTP/1.1
content-type: application/json

{
  "id": 51,
  "title": "Updated movie",
  "genre": "Documentary",
  "release_year": 1900,
  "poster": null,
  "trailer": null,
  "storyline": "",
  "actors": ["Tom Skerritt", "Bill Paxton", "Elijah Wood"], 
  "directors": ["Mel Gibson"],  
  "studios": ["Walt Disney Pictures", "Marvel Studios"]  
}

### Patch movie
PATCH http://localhost:5000/api/movies/51 HTTP/1.1
content-type: application/json

{
  "title": "Patched movie",
  "genre": "Adventure",
  "release_year": 1850,
  "storyline": null,
  "actors": ["Tom Skerritt", "Patrick McGoohan", "Elijah Wood"], 
  "studios": ["Marvel Studios"] 
}

### Delete movie
DELETE  http://localhost:5000/api/movies/51 HTTP/1.1
